# Generated by Django 5.2 on 2025-05-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstudy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
